# Generated by Django 3.2.17 on 2023-02-11 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GermanToEnglishDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=64)),
                ('base_word_length', models.IntegerField(null=True)),
                ('form', models.CharField(max_length=32, null=True)),
                ('definition', models.CharField(max_length=256)),
                ('search_key', models.CharField(max_length=64)),
            ],
        ),
    ]
